### PR TITLE
Add configurable timeout to search app

### PR DESCRIPTION
**Pull request by lennartack**
@bartjkdp  Can we make a test image from this?

### CODE REVIEW

**Comment by bartjkdp** [comment]
@lennartack if you rebase your change on https://github.com/delta10/signalen-backend/tree/release/2.33.0, a Docker image is built. If you tag the commit, a Docker image is pushed as well.

**Comment by lennartack** [comment]
@bartjkdp I tested the image and it works. Make a pull request to Amsterdam/Signalen now?

**Comment by bartjkdp** [comment]
@lennartack yes, you can create PR to Amsterdam/Signalen. I think we need to motivate the requested change in the PR, so the developers of Amsterdam know what our problem is.

**Comment by bartjkdp** [comment]
Merged in upstream.

**Pull request closed without merging**
